name = "portoflio"
compatibility_date = "2025-06-12"
routes = [
    { pattern = "irsyad.dev/*", zone_name = "irsyad.dev" },
    { pattern = "www.irsyad.dev/*", zone_name = "irsyad.dev" }
]

[assets]
directory = "./dist/"
html_handling = "drop-trailing-slash"
not_found_handling = "404-page"